# Generated by Django 5.0.1 on 2024-02-06 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_cart_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='is_order_placed',
        ),
    ]
