# Generated by Django 5.0.1 on 2024-02-07 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_remove_cart_is_order_placed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='sub_total',
            field=models.FloatField(),
        ),
    ]
