# Generated by Django 5.0.1 on 2024-02-07 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_cartitems_cart_alter_cartitems_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='sub_total',
        ),
        migrations.RemoveField(
            model_name='cartitems',
            name='total_price',
        ),
    ]
