# Generated by Django 4.2.7 on 2024-02-11 18:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0009_order_orderedproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderedproduct',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordered_products', to=settings.AUTH_USER_MODEL),
        ),
    ]
