# Generated by Django 4.2.7 on 2024-02-11 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_alter_orderedproduct_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.IntegerField(choices=[(1, 'ORDER_CONFIRMED'), (2, 'ORDER_SHIPPED'), (3, 'ORDER_DELIVERED'), (-1, 'ORDER_CANCELLED')], default=1),
        ),
    ]
