# Generated by Django 4.2.7 on 2024-02-11 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_orderitem_delete_orderedproduct_order_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order_status',
            field=models.IntegerField(choices=[(1, 'Confirmed'), (2, 'Shipped'), (3, 'Delivered'), (-1, 'Cancelled')], default=1),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
