# Generated by Django 4.2.7 on 2024-02-12 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_orderitem_created_at_orderitem_order_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='address',
            field=models.CharField(default='exit', max_length=50),
            preserve_default=False,
        ),
    ]
