# Generated by Django 4.2.7 on 2024-02-12 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_orderitem_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='order_status',
            field=models.IntegerField(choices=[(1, 'Confirmed'), (2, 'Shipped'), (3, 'Delivered'), (-1, 'Cancelled'), (-2, 'Seller Cancelled')], default=1),
        ),
    ]
