# Generated by Django 4.2.7 on 2024-02-14 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0018_returnorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnorder',
            name='return_status',
            field=models.IntegerField(choices=[(1, 'Return Requested'), (2, 'Returned')], default=1),
        ),
    ]
