# Generated by Django 4.2.7 on 2024-02-14 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0019_returnorder_return_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='order_status',
            field=models.IntegerField(choices=[(1, 'Confirmed'), (2, 'Shipped'), (3, 'Delivered'), (-1, 'Cancelled'), (-2, 'Cancelled by Seller'), (4, 'Return Requested'), (5, 'Returned')], default=1),
        ),
    ]
