# Generated by Django 5.0.1 on 2024-01-19 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_verifiled',
            field=models.BooleanField(default=False),
        ),
    ]
