# Generated by Django 5.0.1 on 2024-01-20 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_customer_is_verifiled'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='otp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
