# Generated by Django 5.0.1 on 2024-01-20 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_customer_otp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='is_verifiled',
            new_name='is_verified',
        ),
    ]
