# Generated by Django 4.2.7 on 2024-02-10 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_rename_is_verifiled_customer_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='country',
        ),
    ]
