# Generated by Django 5.0.1 on 2024-02-29 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0005_categoryoffer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoryOffer',
        ),
    ]
