# Generated by Django 5.0.1 on 2024-03-02 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='banner images/'),
        ),
    ]
