# Generated by Django 5.0.1 on 2024-03-02 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0004_banner_banner_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='is_listed',
            field=models.BooleanField(default=True),
        ),
    ]
