# Generated by Django 5.0.1 on 2024-01-23 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('product', '0003_alter_product_brand_alter_productimage_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='category.brand'),
        ),
        migrations.AddField(
            model_name='product',
            name='back_camera',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='display',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='front_camera',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='processor',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='processor_brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='category.processorbrand'),
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
    ]
