# Generated by Django 5.0.1 on 2024-01-24 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_brand_product_back_camera_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='battery_capacity',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
