# Generated by Django 5.0.1 on 2024-01-24 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_battery_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='product images/', verbose_name='Product Image'),
        ),
    ]
