# Generated by Django 5.0.1 on 2024-01-25 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_productimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('mobile', 'mobile'), ('laptop', 'laptop'), ('all', 'All')], default='all', max_length=10),
        ),
    ]
