# Generated by Django 5.0.1 on 2024-01-25 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productvariant',
            old_name='varient_name',
            new_name='variant_name',
        ),
    ]
