# Generated by Django 5.0.1 on 2024-01-26 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('product', '0008_rename_varient_name_productvariant_variant_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='category.brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('mobile', 'mobile'), ('laptop', 'laptop')], max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='display',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='processor_brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.processorbrand'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product images/', verbose_name='Product Image'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='colour',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Product Colour'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='ram',
            field=models.CharField(choices=[('512MB', '512MB'), ('1GB', '1GB'), ('2GB', '2GB'), ('4GB', '4GB'), ('6GB', '6GB'), ('8GB', '8GB'), ('12GB', '12GB'), ('16GB', '16GB'), ('32GB', '32GB')], verbose_name='RAM'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='storage',
            field=models.CharField(choices=[('64GB', '64GB'), ('16GB', '16GB'), ('32GB', '32GB'), ('64GB', '64GB'), ('128GB', '128GB'), ('256GB', '256GB'), ('512GB', '512GB'), ('1TB', '1TB'), ('2TB', '2TB')], verbose_name='Internal Storage'),
        ),
    ]
