# Generated by Django 5.0.1 on 2024-01-26 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_product_brand_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='is_listed',
            field=models.BooleanField(default=True),
        ),
    ]
