# Generated by Django 5.0.1 on 2024-01-29 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_remove_product_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sub_category',
            new_name='category',
        ),
    ]
